### ISSUE TITLE
Build failure about dependencies

### ISSUE THREAD

**Issue by samixchoumi** [Riverside-Software/rules-plugin-template#1]
Hi!

As you can see below : 
https://image.noelshack.com/fichiers/2017/17/1493306081-build-plugin-lang-progress-error-2.png

The dependency for project eu.rssw.sonar.openedge:acme-rules-plugin:sonar-plugin:1.0.0-SNAPSHOT hasn't be found, the others depencies are found by Maven.
No issues about this has been told before. If you have any explanation about this issue, i would be glad to know about it.

**Comment by gquerret** [comment]
The OE plugin artifacts are not pushed to Maven Central, so you need to have them in your local repository. If you worked with the master branch, then you should have version 1.3.12-SNAPSHOT of openedge-checks. Update pom.xml of your rules accordingly.

**Comment by samixchoumi** [comment]
Thanks for the information, i put the correct artifact in my project, but now, after some try, as you can see below, i've some error about finding class or package but in my eclipse/intelliJ project, all is correct.

![build_plugin_lang_progress--error_2 7](https://cloud.githubusercontent.com/assets/22171928/25518882/dff6f074-2bf5-11e7-8625-3a1ad5031dad.png)
