### ISSUE TITLE
Goal excution failed

### ISSUE THREAD

**Issue by samixchoumi** [Riverside-Software/rules-plugin-template#2]
Thanks for the information provided about my previous issue, i put the correct artifact in my project, but now, after some try, as you can see below, i've some error about finding class or package but in my eclipse/intelliJ project, all is correct.
And after checking, all the information wanted are on the project.

I don't know what to do now ...

![build_plugin_lang_progress--error_2 7](https://cloud.githubusercontent.com/assets/22171928/25518882/dff6f074-2bf5-11e7-8625-3a1ad5031dad.png)

**Comment by gquerret** [comment]
Something wrong in your setup, use mvn install on sonar-openedge, then update pom.xml in the rules plugin to match the version number of openedge-checks-shaded, and use mvn package on the rules plugin.
Just tried it, it just worked.
