### ISSUE TITLE
AbstractLineRule doesn't exist

### ISSUE THREAD

**Issue by samixchoumi** [Riverside-Software/rules-plugin-template#3]
I'm testing the template, all is working but i wanted to create a custom rules as shown in the section : Create your custom rule (https://riverside-software.atlassian.net/wiki/display/OESONAR/Write+custom+rules) but the file api.checks.AbstractLintRule doesn't exist anymore.

After compiling 3 times without any change (using `mvn install`), the compilation is good but only the "NoOpRule" appear in the dashboard, the "FooRule" doesn't appear.
![rules1](https://cloud.githubusercontent.com/assets/22171928/25524075/4cb5720e-2c09-11e7-85b2-412279cd9e8f.png)

EDIT : Now i tried the command `mvn clean install` and now the compilation is failing.

**Comment by gquerret** [comment]
Yes, NoOpRule is the only present in the template.
You can use NoOpRule as a test class, you just have to implement your business logic in the execute() method. The ParseUnit parameter will give you access to the AST.
