### ISSUE TITLE
Sensor analysis - connect timed out

### ISSUE THREAD

**Issue by samixchoumi** [Riverside-Software/rules-plugin-template#5]
Hi,

Below you could see what happen when i try to send analytics with `sonar-scanner` for a Progress project. I specify "Progress project" because when i send analytics with `sonar-scanner` for java (example), i got no error and the analysis is done whereas for a Progress project the analysis isn't done but i've a visual on the website without any rules used.

I looked at how you sonar-project.properties is set here : https://riverside-software.atlassian.net/wiki/display/OESONAR/Getting+started and i used the same thing, so what's the difference between a java project and a Progress project ?

> INFO: Unable to send analytics
> java.net.SocketTimeoutException: connect timed out
>         at java.net.DualStackPlainSocketImpl.waitForConnect(Native Method)
>         at java.net.DualStackPlainSocketImpl.socketConnect(DualStackPlainSocketImpl.java:85)
>         at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
>         at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
>         at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
>         at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:172)
>         at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
>         at java.net.Socket.connect(Socket.java:589)
>         at sun.net.NetworkClient.doConnect(NetworkClient.java:175)
>         at sun.net.www.http.HttpClient.openServer(HttpClient.java:432)
>         at sun.net.www.http.HttpClient.openServer(HttpClient.java:527)
>         at sun.net.www.http.HttpClient.<init>(HttpClient.java:211)
>         at sun.net.www.http.HttpClient.New(HttpClient.java:308)
>         at sun.net.www.http.HttpClient.New(HttpClient.java:326)
>         at sun.net.www.protocol.http.HttpURLConnection.getNewHttpClient(HttpURLConnection.java:1202)
>         at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1138)
>         at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1032)
>         at sun.net.www.protocol.http.HttpURLConnection.connect(HttpURLConnection.java:966)
>         at sun.net.www.protocol.http.HttpURLConnection.getOutputStream0(HttpURLConnection.java:1316)
>         at sun.net.www.protocol.http.HttpURLConnection.getOutputStream(HttpURLConnection.java:1291)
>         at org.sonar.plugins.openedge.sensor.OpenEdgeProparseSensor.execute(OpenEdgeProparseSensor.java:196)
>         at org.sonar.scanner.sensor.SensorWrapper.analyse(SensorWrapper.java:53)
>         at org.sonar.scanner.phases.SensorsExecutor.executeSensor(SensorsExecutor.java:57)
>         at org.sonar.scanner.phases.SensorsExecutor.execute(SensorsExecutor.java:49)
>         at org.sonar.scanner.phases.AbstractPhaseExecutor.execute(AbstractPhaseExecutor.java:78)
>         at org.sonar.scanner.scan.ModuleScanContainer.doAfterStart(ModuleScanContainer.java:175)
>         at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:143)
>         at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:128)
>         at org.sonar.scanner.scan.ProjectScanContainer.scan(ProjectScanContainer.java:262)
>         at org.sonar.scanner.scan.ProjectScanContainer.scanRecursively(ProjectScanContainer.java:257)
>         at org.sonar.scanner.scan.ProjectScanContainer.doAfterStart(ProjectScanContainer.java:247)
>         at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:143)
>         at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:128)
>         at org.sonar.scanner.task.ScanTask.execute(ScanTask.java:47)
>         at org.sonar.scanner.task.TaskContainer.doAfterStart(TaskContainer.java:86)
>         at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:143)
>         at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:128)
>         at org.sonar.scanner.bootstrap.GlobalContainer.executeTask(GlobalContainer.java:118)
>         at org.sonar.batch.bootstrapper.Batch.executeTask(Batch.java:117)
>         at org.sonarsource.scanner.api.internal.batch.BatchIsolatedLauncher.execute(BatchIsolatedLauncher.java:63)
>         at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
>         at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
>         at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
>         at java.lang.reflect.Method.invoke(Method.java:498)
>         at org.sonarsource.scanner.api.internal.IsolatedLauncherProxy.invoke(IsolatedLauncherProxy.java:60)
>         at com.sun.proxy.$Proxy0.execute(Unknown Source)
>         at org.sonarsource.scanner.api.EmbeddedScanner.doExecute(EmbeddedScanner.java:233)
>         at org.sonarsource.scanner.api.EmbeddedScanner.runAnalysis(EmbeddedScanner.java:151)
>         at org.sonarsource.scanner.cli.Main.runAnalysis(Main.java:123)
>         at org.sonarsource.scanner.cli.Main.execute(Main.java:77)
>         at org.sonarsource.scanner.cli.Main.main(Main.java:61)

**Comment by gquerret** [comment]
The OpenEdge sensors send a few metrics (number of OE files analyzed, number of failures, and execution time per rule) to a server. Message and stack trace is here for information purpose.

**Comment by samixchoumi** [comment]
So why i didn't get any issue on the dashboard with my rules if the problem isn't the OpenEdge Sensor ?

**Comment by gquerret** [comment]
By just using this code in NoOpRule.java:
```
  @Override
  public void execute(InputFile file, ParseUnit o) {
    reportIssue(file, 1, "xxx");
  }
```
I'm getting an issue on each file, at line number 1.
If this doesn't work, then have a look at your configuration. Especially, if your rule activated in the quality profile.
If it works, then this is coming from your business logic. Introduce log messages during the analysis. Use your favorite debugger. We can also deliver trainings, which might be the best solution.

**Comment by samixchoumi** [comment]
As you can see below, my configuration is fine, but i got 0 issue ...
![nothing happened](https://cloud.githubusercontent.com/assets/22171928/25620375/765aa780-2f4e-11e7-9c4d-7265325111c0.png)

How can we have training about rules development, i'm interested about it?

So i tried on the acme version (without any change except dependency and test), it works fine, but i'm comparing my own testing version and i don't find any problems, because it's exactly the same rule ..

![image](https://cloud.githubusercontent.com/assets/22171928/25621275/3c8d505e-2f51-11e7-8083-9778b61ae847.png)

**Comment by samixchoumi** [comment]
So i tried on the acme version (without any change except dependency and test), it works fine, but i'm comparing my own testing version and i don't find any problems, because it's exactly the same rule ..

![image](https://cloud.githubusercontent.com/assets/22171928/25621275/3c8d505e-2f51-11e7-8083-9778b61ae847.png)

**Comment by gquerret** [comment]
About trainings: you can call me directly on my mobile phone, you'll find the number in my signature. Tomorrow morning will be OK.
